# Generated by Django 4.1.3 on 2022-11-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='BachelorsDegreeAddresses',
        ),
    ]
