# Generated by Django 4.1.3 on 2023-06-15 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Student index number')),
                ('program', models.CharField(max_length=30, verbose_name='Program of study')),
                ('email', models.CharField(max_length=60, verbose_name='Email address')),
                ('level', models.IntegerField(default=100, verbose_name='Level of study')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create at')),
            ],
        ),
    ]
