# Generated by Django 4.2.2 on 2023-06-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='computer science ', max_length=30, verbose_name='department name')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DIP', 'Diploma'), ('HND', 'Higher National Diplomas'), ('BTECH', 'Bachelor of Technology')], default='BTECH', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentmanager.department')),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('index', models.IntegerField(verbose_name='Student index number')),
                ('email', models.CharField(max_length=60, unique=True, verbose_name='Email address')),
                ('level', models.IntegerField(default=100, verbose_name='Level of study')),
                ('year_enrolled', models.IntegerField(default=2023, verbose_name='Year enrolled')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentmanager.program', verbose_name='Program of study')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
