# Generated by Django 4.2.2 on 2023-06-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
