# Generated by Django 4.2.2 on 2023-06-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanager', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentmanager.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentmanager.program', verbose_name='Program of study'),
        ),
    ]
