# Generated by Django 4.2.2 on 2023-06-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanager', '0004_program_department_student_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=60, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.IntegerField(blank=True, verbose_name='Student index number'),
        ),
    ]
