# Generated by Django 4.2.2 on 2023-07-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanager', '0005_alter_student_email_alter_student_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(choices=[('DIP', 'Diploma'), ('HND', 'Higher National Diplomas'), ('bcict', 'Bachelor of Technology')], default='bcict', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='student', max_length=50),
        ),
    ]
