# Generated by Django 5.0 on 2023-12-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=10)),
                ('year_enrolled', models.CharField(max_length=4)),
                ('graduation_year', models.CharField(max_length=4)),
            ],
        ),
    ]
