# Generated by Django 5.0 on 2023-12-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('year_enrolled', models.IntegerField()),
            ],
        ),
    ]
