# Generated by Django 5.0 on 2023-12-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
