# Generated by Django 5.0 on 2023-12-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0002_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, default='Unknown Course', max_length=20),
        ),
    ]
