# Generated by Django 4.2.2 on 2023-09-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0003_remove_department_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
