# Generated by Django 4.2.2 on 2023-09-05 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_student_department_student_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='ict', max_length=30),
        ),
        migrations.AlterField(
            model_name='program',
            name='abbreviation',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student_management.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student_management.faculty'),
        ),
    ]
