# Generated by Django 4.2.2 on 2023-09-05 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0005_alter_program_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='isInSchool',
            field=models.BooleanField(default=True),
        ),
    ]
