# Generated by Django 4.2.2 on 2023-09-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0006_alter_student_department_alter_student_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
    ]
