# Generated by Django 4.2.2 on 2023-09-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0007_remove_student_department_remove_student_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='name',
            new_name='faculty_name',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='abbreviation',
            new_name='program_abbreviation',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='program_name',
        ),
    ]
